language: generic
sudo: required
services:
  - docker
env:
  - DOCKER_TAG=archlinux-x64 CXX=clang++ BUILD_TYPE=Debug
  - DOCKER_TAG=archlinux-x64 CXX=clang++ BUILD_TYPE=Release
  - DOCKER_TAG=archlinux-x64 CXX=g++ BUILD_TYPE=Debug
  - DOCKER_TAG=archlinux-x64 CXX=g++ BUILD_TYPE=Release

before_install:
  - docker pull oneup40/oneup-gb-build:${DOCKER_TAG}

script:
  - docker run -e CXX=${CXX} -v $(pwd):/project oneup40/oneup-gb-build:archlinux-x64 /bin/sh -c "cmake /project -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -GNinja && cmake --build . && ninja test"
